

service: dark-aws-golang

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get

  create:
    handler: bin/create 
    events:
      - http:
          path: character 
          method: post
          cors: true